# Generated by Django 2.1 on 2018-11-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20181111_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Phone, Elecronics.....', max_length=100),
        ),
    ]
